package com.igurman.gur_car_bot.constant;

public enum RouteType {
    UNKNOWN,
    START_ROUTE,
    MENU_ROUTE,
    ABOUT_ROUTE,
    CATALOG_ROUTE,
    CONTACT_ROUTE,
    HELP_ROUTE,
    SETTINGS_ROUTE,
    QUESTION_ROUTE,
    ABOUT_MENU_ROUTE,
    CATALOG_MENU_ROUTE,
    CONTACT_MENU_ROUTE,
    HELP_MENU_ROUTE,
    SETTINGS_MENU_ROUTE,
    QUESTION_MENU_ROUTE,
    CATALOG_MAKE_ROUTE,
    CATALOG_MODEL_ROUTE,
    WRITE_TO_ADMIN_ROUTE,
    CATALOG_FILTER_ROUTE,
    CATALOG_YEAR_ROUTE,
    CATALOG_ODOMETER_ROUTE,
    CATALOG_ENGINE_TYPE_ROUTE,
    CATALOG_PRICE_ROUTE,
    CATALOG_GRADE_ROUTE,
    CATALOG_SEARCH_ROUTE,
    CATALOG_ORDER_ROUTE,
    SETTINGS_LANGUAGE_ROUTE,
    SETTINGS_CITY_ROUTE,
    SETTINGS_DISTANCE_ROUTE,
    SETTINGS_TAX_ROUTE,
    QUESTION_CANCEL_ROUTE,
    MIGRATE_ROUTE,



}
